### ISSUE TITLE
Merge into zsh-completions project ?

### ISSUE THREAD

**Issue by nicoulaj** [zchee/zsh-completions#3]
We have a community completions repository [here](https://github.com/zsh-users/zsh-completions), maybe some of the completions could be added?

**Comment by zchee** [comment]
@nicoulaj Hi, sorry for the very late reply.

Yeah, I planned my wrote some completion scripts to send a pull request to you said repository at the first time of creating this repo.
However, I usually use some CLI tools to *HEAD* version. such as `go`, LLVM compiler runtime.
e.g., In Go programming language (It's My first language), I was compiling from master branch's source every day (In Go community, it called `devel` version). And I will do edit completion script if added new flags to some commands.
It means, My script not compatible Go *stable* version. If some Go users who are using the stable version will display devel flags, but can't use it. Any flags not merged yet to stable.

I think zsh-completion community must be respect to the some CLI stable version IMO. Therefore I didn't send PR to that repository.
Do you think about it?

---

But certainly, there are some commands which already stable and seems to new flags will not be added. like macOS built-in commands or etc.
It may be those command completion scripts should send PR.  However, I don't have much knowledge of how to write(readable, fast, etc) zsh completion and I don't know if I have enough time to fix to reviews point the PR I sent. If you're fine with that, I'll send a pull request for some command completion scripts.

Alternatively, you (or zsh-completion maintainers) can copy from this repository. Note that all scripts wrote in the BSD license. But if you want to copy to the community repository but have license concerns, I'll abandon that license.
Any idea?
